### PR TITLE
Fix/lbbniu/rbac

### LINKED ISSUE #107: rbac 权限问题
image

### PR DESCRIPTION
**Pull request by lbbniu**
**Please provide issue(s) of this PR:**
Fixes #107

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Docs
- [ ] Inject Sidecar
- [x] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by chuntaojun** [comment]
pls link issue

**Comment by lbbniu** [comment]
> pls link issue

image

**Comment by chuntaojun** [comment]
> > pls link issue
> 
> image

麻烦单独创建一个 issue，并关联这个 PR，而不要直接提交 PR

**Comment by lbbniu** [comment]
> > > pls link issue
> > 
> > 
> > image
> 
> 麻烦单独创建一个 issue，并关联这个 PR，而不要直接提交 PR

添加了issue

**Pull request merged**
